rem   *** validation ***
call scripts\run-validator-tests.bat
call scripts\run-checker-tests.bat

rem    *** samples ***
md samples
call scripts\gen-answer.bat samples\01 samples\01.a "samples" ""

rem    *** tests ***
md tests
call scripts\gen-input-via-files.bat "..\files\gen34.exe 1 5" "tests\05:tests\06:tests\07:tests\08" "5:6:7:8"
call scripts\gen-input-via-files.bat "..\files\gen34.exe 5 37" "tests\37:tests\38:tests\39:tests\40" "37:38:39:40"
call scripts\gen-input-via-files.bat "..\files\genSpecial.exe 3000 21" "tests\21:tests\22:tests\23:tests\24" "21:22:23:24"
call scripts\gen-input-via-files.bat "..\files\genRand.exe 300 1" "tests\01:tests\02:tests\03:tests\04" "1:2:3:4"
call scripts\gen-input-via-files.bat "..\files\gen34.exe 2 17" "tests\17:tests\18:tests\19:tests\20" "17:18:19:20"
call scripts\gen-input-via-files.bat "..\files\genSpecial.exe 100000 41" "tests\41:tests\42:tests\43:tests\44" "41:42:43:44"
call scripts\gen-input-via-files.bat "..\files\genRand.exe 3000 13" "tests\13:tests\14:tests\15:tests\16" "13:14:15:16"
call scripts\gen-input-via-files.bat "..\files\gen34.exe 4 29" "tests\29:tests\30:tests\31:tests\32" "29:30:31:32"
call scripts\gen-input-via-files.bat "..\files\genRand.exe 100000 33" "tests\33:tests\34:tests\35:tests\36" "33:34:35:36"
call scripts\gen-input-via-files.bat "..\files\gen34.exe 3 25" "tests\25:tests\26:tests\27:tests\28" "25:26:27:28"
call scripts\gen-input-via-files.bat "..\files\genSpecial.exe 300 9" "tests\09:tests\10:tests\11:tests\12" "9:10:11:12"
call scripts\gen-answer.bat tests\01 tests\01.a "tests" "subtask1"
call scripts\gen-answer.bat tests\02 tests\02.a "tests" "subtask1"
call scripts\gen-answer.bat tests\03 tests\03.a "tests" "subtask1"
call scripts\gen-answer.bat tests\04 tests\04.a "tests" "subtask1"
call scripts\gen-answer.bat tests\05 tests\05.a "tests" "subtask1"
call scripts\gen-answer.bat tests\06 tests\06.a "tests" "subtask1"
call scripts\gen-answer.bat tests\07 tests\07.a "tests" "subtask1"
call scripts\gen-answer.bat tests\08 tests\08.a "tests" "subtask1"
call scripts\gen-answer.bat tests\09 tests\09.a "tests" "subtask1"
call scripts\gen-answer.bat tests\10 tests\10.a "tests" "subtask1"
call scripts\gen-answer.bat tests\11 tests\11.a "tests" "subtask1"
call scripts\gen-answer.bat tests\12 tests\12.a "tests" "subtask1"
call scripts\gen-answer.bat tests\13 tests\13.a "tests" "subtask2"
call scripts\gen-answer.bat tests\14 tests\14.a "tests" "subtask2"
call scripts\gen-answer.bat tests\15 tests\15.a "tests" "subtask2"
call scripts\gen-answer.bat tests\16 tests\16.a "tests" "subtask2"
call scripts\gen-answer.bat tests\17 tests\17.a "tests" "subtask2"
call scripts\gen-answer.bat tests\18 tests\18.a "tests" "subtask2"
call scripts\gen-answer.bat tests\19 tests\19.a "tests" "subtask2"
call scripts\gen-answer.bat tests\20 tests\20.a "tests" "subtask2"
call scripts\gen-answer.bat tests\21 tests\21.a "tests" "subtask2"
call scripts\gen-answer.bat tests\22 tests\22.a "tests" "subtask2"
call scripts\gen-answer.bat tests\23 tests\23.a "tests" "subtask2"
call scripts\gen-answer.bat tests\24 tests\24.a "tests" "subtask2"
call scripts\gen-answer.bat tests\25 tests\25.a "tests" "subtask3"
call scripts\gen-answer.bat tests\26 tests\26.a "tests" "subtask3"
call scripts\gen-answer.bat tests\27 tests\27.a "tests" "subtask3"
call scripts\gen-answer.bat tests\28 tests\28.a "tests" "subtask3"
call scripts\gen-answer.bat tests\29 tests\29.a "tests" "subtask4"
call scripts\gen-answer.bat tests\30 tests\30.a "tests" "subtask4"
call scripts\gen-answer.bat tests\31 tests\31.a "tests" "subtask4"
call scripts\gen-answer.bat tests\32 tests\32.a "tests" "subtask4"
call scripts\gen-answer.bat tests\33 tests\33.a "tests" "subtask5"
call scripts\gen-answer.bat tests\34 tests\34.a "tests" "subtask5"
call scripts\gen-answer.bat tests\35 tests\35.a "tests" "subtask5"
call scripts\gen-answer.bat tests\36 tests\36.a "tests" "subtask5"
call scripts\gen-answer.bat tests\37 tests\37.a "tests" "subtask5"
call scripts\gen-answer.bat tests\38 tests\38.a "tests" "subtask5"
call scripts\gen-answer.bat tests\39 tests\39.a "tests" "subtask5"
call scripts\gen-answer.bat tests\40 tests\40.a "tests" "subtask5"
call scripts\gen-answer.bat tests\41 tests\41.a "tests" "subtask5"
call scripts\gen-answer.bat tests\42 tests\42.a "tests" "subtask5"
call scripts\gen-answer.bat tests\43 tests\43.a "tests" "subtask5"
call scripts\gen-answer.bat tests\44 tests\44.a "tests" "subtask5"

